language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - python setup.py develop
  - pip install coverage

script: nosetests -v --with-coverage --cover-package=jiebarpc

after_success:
  - pip install coveralls
  - coveralls
